# PART A

#### Name: Ishu Goyal

$$ \\ $$

-Computation of homography matrix by using the pixel coordinates of the corresponding points in the image.

-Homography matrix 'h' will convert the image pixel coordinates from the source image to the destination image by projecting the points from source image plane to destination image plane.



In [1]:
import numpy as np

## Creating image points list

---------------------

-Creating list of corresponding points of same features from both the images

- xs - X coordinates of the image pixel position from source image
- ys - Y coordinates of the image pixel position from source image
- xd - X coordinates of the image pixel position from the destination image
- yd - Y coordinates of the image pixel position from the destination image

In [2]:
xs = [365.6942, 368.1937, 366.9331, 364.2767,362.9518,361.6201,360.1071,419.5753,418.3222,416.9176,415.6446,414.2065,412.7598,411.2062,471.1135,469.6650,468.1966,466.7643,465.3264,463.9024,462.3837,522.7403,521.1732,519.8360, 518.3030]
ys = [292.5464, 188.3461, 240.6366, 344.1300,395.6568,447.0891,498.7948,189.8007,242.0051,293.9554,345.5727,397.0850,448.6121,500.3589,191.0175,243.2864,295.2578,346.9755,398.6040,450.2090,502.0514,192.2352,244.5373,296.6545,348.4220]
xd = [348.5998, 377.6357, 319.0576, 406.4299, 435.1823, 463.8352, 492.4751, 361.0885, 390.4941, 419.5286, 448.2632, 477.0448, 505.5887, 534.1678, 403.1739, 432.2963, 461.3121, 490.0896, 518.6993, 547.2607, 575.9412, 445.1797, 474.2915, 503.2628, 531.9940]
yd = [454.3980, 370.0124, 412.3830, 496.2708, 537.9025, 579.5414, 621.3035, 341.5682, 383.8370, 426.0496, 467.8811, 509.6456, 551.1746, 593.2059, 312.8976, 355.4028, 397.6080, 439.5705, 481.2976, 523.1167, 564.9918, 284.1512, 326.7610, 369.0763, 411.0553]

### Check (each list has 25 features or not)


In [24]:
print(len(xs),len(ys),len(xd),len(yd))

25 25 25 25


# Once we have the image points now we will solve for homography

$$\begin{bmatrix} xd \\ yd \\ 1 \end{bmatrix} \equiv  \begin{bmatrix} xd \\ yd \\ zd \end{bmatrix} = \begin{bmatrix} h_{11} & h_{12} & h_{13} \\ h_{21} & h_{22} & h_{23} \\ h_{31} & h_{32} & h_{33} \end{bmatrix} \begin{bmatrix} xs \\ ys \\ 1 \end{bmatrix}$$ 

For actual points from homogenous representation: 
$$ \frac{xd^{(i)}}{zd^{(i)}} and \frac{yd^{(i)}}{zd^{(i)}}$$

A.h=0

$$\begin{bmatrix} xs^{(i)} & ys^{(i)} & 1 & 0 & 0 & 0 & -xd^{(i)}xs^{(i)} & -xd^{(i)}ys^{(i)} & -xd^{(i)} \\ 0 & 0 & 0 & xs^{(i)} & ys^{(i)} & 1 & -yd^{(i)}xs^{(i)} & -yd^{(i)}ys^{(i)} & -yd^{(i)} \end{bmatrix} \begin{bmatrix} h_{11} \\ h_{12} \\ h_{13} \\ h_{21} \\ h_{22} \\ h_{23} \\ h_{31} \\ h_{32} \\ h_{33} \end{bmatrix} =\begin{bmatrix} 0 \\ 0 \end{bmatrix} $$   

Equation for one point

$$\begin{bmatrix} xs^{(1)} & ys^{(1)} & 1 & 0 & 0 & 0 & -xd^{(1)}xs^{(1)} & -xd^{(1)}ys^{(1)} & -xd^{(1)} \\ 0 & 0 & 0 & xs^{(1)} & ys^{(1)} & 1 & -yd^{(1)}xs^{(1)} & -yd^{(1)}ys^{(1)} & -yd^{(1)} \\ xs^{(2)} & ys^{(2)} & 1 & 0 & 0 & 0 & -xd^{(2)}xs^{(2)} & -xd^{(2)}ys^{(2)} & -xd^{(2)} \\ 0 & 0 & 0 & xs^{(2)} & ys^{(2)} & 1 & -yd^{(2)}xs^{(2)} & -yd^{(2)}ys^{(2)} & -yd^{(2)} \\ xs^{(3)} & ys^{(3)} & 1 & 0 & 0 & 0 & -xd^{(3)}xs^{(3)} & -xd^{(3)}ys^{(3)} & -xd^{(3)} \\ 0 & 0 & 0 & xs^{(3)} & ys^{(3)} & 1 & -yd^{(3)}xs^{(3)} & -yd^{(3)}ys^{(3)} & -yd^{(3)} \\ xs^{(4)} & ys^{(4)} & 1 & 0 & 0 & 0 & -xd^{(4)}xs^{(4)} & -xd^{(4)}ys^{(4)} & -xd^{(4)} \\ 0 & 0 & 0 & xs^{(4)} & ys^{(4)} & 1 & -yd^{(4)}xs^{(4)} & -yd^{(4)}ys^{(4)} & -yd^{(4)} \\ xs^{(5)} & ys^{(5)} & 1 & 0 & 0 & 0 & -xd^{(5)}xs^{(5)} & -xd^{(5)}ys^{(5)} & -xd^{(5)} \\ 0 & 0 & 0 & xs^{(5)} & ys^{(5)} & 1 & -yd^{(5)}xs^{(5)} & -yd^{(5)}ys^{(5)} & -yd^{(5)} \\ xs^{(6)} & ys^{(6)} & 1 & 0 & 0 & 0 & -xd^{(6)}xs^{(6)} & -xd^{(6)}ys^{(6)} & -xd^{(6)} \\ 0 & 0 & 0 & xs^{(6)} & ys^{(6)} & 1 & -yd^{(6)}xs^{(6)} & -yd^{(6)}ys^{(6)} & -yd^{(6)} \\ xs^{(7)} & ys^{(7)} & 1 & 0 & 0 & 0 & -xd^{(7)}xs^{(7)} & -xd^{(7)}ys^{(7)} & -xd^{(7)} \\ 0 & 0 & 0 & xs^{(7)} & ys^{(7)} & 1 & -yd^{(7)}xs^{(7)} & -yd^{(7)}ys^{(7)} & -yd^{(7)} \\ xs^{(8)} & ys^{(8)} & 1 & 0 & 0 & 0 & -xd^{(8)}xs^{(8)} & -xd^{(8)}ys^{(8)} & -xd^{(8)} \\ 0 & 0 & 0 & xs^{(8)} & ys^{(8)} & 1 & -yd^{(8)}xs^{(8)} & -yd^{(8)}ys^{(8)} & -yd^{(8)}
\\ xs^{(9)} & ys^{(9)} & 1 & 0 & 0 & 0 & -xd^{(9)}xs^{(9)} & -xd^{(9)}ys^{(9)} & -xd^{(9)} \\ 0 & 0 & 0 & xs^{(9)} & ys^{(9)} & 1 & -yd^{(9)}xs^{(9)} & -yd^{(9)}ys^{(9)} & -yd^{(9)}
\\ xs^{(10)} & ys^{(10)} & 1 & 0 & 0 & 0 & -xd^{(10)}xs^{(10)} & -xd^{(10)}ys^{(10)} & -xd^{(10)} \\ 0 & 0 & 0 & xs^{(10)} & ys^{(10)} & 1 & -yd^{(10)}xs^{(10)} & -yd^{(10)}ys^{(10)} & -yd^{(10)}
\\ ... & ... & ... & ... & ... & ... & ... & ... & ... \\
xs^{(25)} & ys^{(25)} & 1 & 0 & 0 & 0 & -xd^{(25)}xs^{(25)} & -xd^{(25)}ys^{(25)} & -xd^{(25)} \\ 0 & 0 & 0 & xs^{(25)} & ys^{(25)} & 1 & -yd^{(25)}xs^{(25)} & -yd^{(25)}ys^{(25)} & -yd^{(25)}
\end{bmatrix} \begin{bmatrix} h_{11} \\ h_{12} \\ h_{13} \\ h_{21} \\ h_{22} \\ h_{23} \\ h_{31} \\ h_{32} \\ h_{33} \end{bmatrix} =\begin{bmatrix} 0 \\ 0 \end{bmatrix} $$  


#### Solving for h.

In [25]:
#xs, ys, 1, 0, 0, 0, -xdxs, -xdys, -xd
#0, 0, 0, xs, ys, 1, -ydxs, -ydys, -yd
xdxs=-np.multiply(np.array(xd),np.array(xs))
xdys =-np.multiply(np.array(xd),np.array(ys)) 
ydxs=-np.multiply(np.array(yd),np.array(xs))
ydys=-np.multiply(np.array(yd),np.array(ys))

In [8]:
A=[]
for i in range(0,25):
    mat1 = [xs[i],ys[i],1,0,0,0,xdxs[i],xdys[i],-xd[i]]
    mat2 = [0,0,0,xs[i],ys[i],1,ydxs[i],ydys[i],-yd[i]]
    A.append(mat1)
    A.append(mat2)

In [9]:
A = np.array(A)

In [10]:
A.shape

(50, 9)

## Finding Value of H

Solve for **h** such that:
<br>
$$A.h = 0 \space and \space \lvert\lvert h \rvert\rvert = 0$$

Loss function L(h):

$$L(h,\lambda) = h^TA^TAh - \lambda(h^Th-1)$$

After First derivative:

$$ 2A^TAh - 2\lambda h = 0$$

We can set it up as a Eigen Value Decomposition of the inner product of matrix A:

$$A^TAh = \lambda h$$

The Eigenvector *h* belongs to the smallest eigenvalue of $\lambda$ of matrix $A^TA$ minimizes the loss function $L(h)$.

In [11]:
inner_product = np.dot(A.T,A)

In [12]:
inner_product.shape

(9, 9)

In [13]:
w, v = np.linalg.eig(inner_product)

In [14]:
w

array([3.37660628e+12, 8.88507868e+10, 7.52466113e+06, 2.72675590e+05,
       1.25530360e+05, 2.08438813e+04, 4.86585786e+03, 3.53287397e-02,
       6.67508712e-03])

In [15]:
v = v.T # transpose 

In [16]:
w/w[0]

array([1.00000000e+00, 2.63136355e-02, 2.22846862e-06, 8.07543337e-08,
       3.71764872e-08, 6.17302686e-09, 1.44104982e-09, 1.04627951e-14,
       1.97686273e-15])

In [17]:
v_prime = v[-1]

In [18]:
h = v_prime.reshape((3,3))

####  Reshaping the last column i.e  homography matrix *h*

In [19]:
h

array([[ 9.50905484e-04,  2.56054818e-04, -6.26685154e-01],
       [ 1.33554769e-03,  1.97839426e-04, -7.79268783e-01],
       [ 2.63043006e-06,  9.43838252e-07, -1.75731232e-03]])

### Verification Check for homography matrix obtained 

In [20]:
product = np.dot(h, np.array([368.1937, 188.3461, 1]).T)

In [21]:
product

array([-0.22834082, -0.25026625, -0.00061104])

In [22]:
product = product / product[2]

In [23]:
product

array([373.69436771, 409.57674259,   1.        ])